-- -------------------------------------------------------------
-- 
-- File Name: D:\Salukat\Development\Software\Quartus\MAX_10_Plus\fft_index\max_10_frequency_index\DC_Blocker.vhd
-- Created: 2021-02-21 20:02:10
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DC_Blocker
-- Source Path: max_10_frequency_index/max_10_index_frequency/DC_Blocker/DC Blocker
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DC_Blocker IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        in0                               :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        out0                              :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12
        );
END DC_Blocker;


ARCHITECTURE rtl OF DC_Blocker IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT dsp_FIRFilter
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dsp_FIRFilter_in                :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          dsp_FIRFilter_out               :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dsp_FIRFilter
    USE ENTITY work.dsp_FIRFilter(rtl);

  -- Signals
  SIGNAL in0_signed                       : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL varargout_1                      : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL varargout_1_signed               : signed(28 DOWNTO 0);  -- sfix29_En15
  SIGNAL out0_tmp                         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL p1y_sub_cast                     : signed(29 DOWNTO 0);  -- sfix30_En15
  SIGNAL p1y_sub_cast_1                   : signed(29 DOWNTO 0);  -- sfix30_En15
  SIGNAL p1y_sub_temp                     : signed(29 DOWNTO 0);  -- sfix30_En15

BEGIN
  -- HDL code generation from MATLAB function: DCBlocker_stepImpl
  u_dsp_FIRFilter : dsp_FIRFilter
    PORT MAP( clk => clk,
              enb => enb,
              dsp_FIRFilter_in => in0,  -- sfix12
              dsp_FIRFilter_out => varargout_1  -- sfix29_En15
              );

  in0_signed <= signed(in0);

  varargout_1_signed <= signed(varargout_1);

  p1y_sub_cast <= resize(in0_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  p1y_sub_cast_1 <= resize(varargout_1_signed, 30);
  p1y_sub_temp <= p1y_sub_cast - p1y_sub_cast_1;
  
  out0_tmp <= "011111111111" WHEN ((p1y_sub_temp(29) = '0') AND (p1y_sub_temp(28 DOWNTO 26) /= "000")) OR ((p1y_sub_temp(29) = '0') AND (p1y_sub_temp(26 DOWNTO 15) = "011111111111")) ELSE
      "100000000000" WHEN (p1y_sub_temp(29) = '1') AND (p1y_sub_temp(28 DOWNTO 26) /= "111") ELSE
      p1y_sub_temp(26 DOWNTO 15) + ('0' & p1y_sub_temp(14));

  out0 <= std_logic_vector(out0_tmp);

END rtl;

