# TCL File Generated by Component Editor 20.1
# Fri Feb 19 09:42:48 CET 2021
# DO NOT MODIFY


# 
# adc_in2_ch0_converter "adc_in2_ch0_converter" v1.0
# giovanny 2021.02.19.09:42:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module adc_in2_ch0_converter
# 
set_module_property DESCRIPTION ""
set_module_property NAME adc_in2_ch0_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Salukat
set_module_property AUTHOR giovanny
set_module_property DISPLAY_NAME adc_in2_ch0_converter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adc_converter_qip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adc_converter_qip.v VERILOG PATH adc_converter_qip.v TOP_LEVEL_FILE
add_fileset_file pll10.v VERILOG PATH pll10.v
add_fileset_file anain2_converter.v VERILOG PATH anain2_converter/synthesis/anain2_converter.v
add_fileset_file altera_modular_adc_control.sdc SDC PATH anain2_converter/synthesis/submodules/altera_modular_adc_control.sdc
add_fileset_file altera_modular_adc_control.v VERILOG PATH anain2_converter/synthesis/submodules/altera_modular_adc_control.v
add_fileset_file altera_modular_adc_control_avrg_fifo.v VERILOG PATH anain2_converter/synthesis/submodules/altera_modular_adc_control_avrg_fifo.v
add_fileset_file altera_modular_adc_control_fsm.v VERILOG PATH anain2_converter/synthesis/submodules/altera_modular_adc_control_fsm.v
add_fileset_file altera_reset_controller.sdc SDC PATH anain2_converter/synthesis/submodules/altera_reset_controller.sdc
add_fileset_file altera_reset_controller.v VERILOG PATH anain2_converter/synthesis/submodules/altera_reset_controller.v
add_fileset_file altera_reset_synchronizer.v VERILOG PATH anain2_converter/synthesis/submodules/altera_reset_synchronizer.v
add_fileset_file anain2_converter_altpll_0.v VERILOG PATH anain2_converter/synthesis/submodules/anain2_converter_altpll_0.v
add_fileset_file anain2_converter_modular_adc_0.v VERILOG PATH anain2_converter/synthesis/submodules/anain2_converter_modular_adc_0.v
add_fileset_file chsel_code_converter_sw_to_hw.v VERILOG PATH anain2_converter/synthesis/submodules/chsel_code_converter_sw_to_hw.v
add_fileset_file fiftyfivenm_adcblock_primitive_wrapper.v VERILOG PATH anain2_converter/synthesis/submodules/fiftyfivenm_adcblock_primitive_wrapper.v
add_fileset_file fiftyfivenm_adcblock_top_wrapper.v VERILOG PATH anain2_converter/synthesis/submodules/fiftyfivenm_adcblock_top_wrapper.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point adc_out
# 
add_interface adc_out conduit end
set_interface_property adc_out associatedClock clock
set_interface_property adc_out associatedReset reset
set_interface_property adc_out ENABLED true
set_interface_property adc_out EXPORT_OF ""
set_interface_property adc_out PORT_NAME_MAP ""
set_interface_property adc_out CMSIS_SVD_VARIABLES ""
set_interface_property adc_out SVD_ADDRESS_GROUP ""

add_interface_port adc_out adc_data rx_in Output 12

