-- -------------------------------------------------------------
-- 
-- File Name: D:\Salukat\Development\Software\Quartus\MAX_10\FFT\max_10_frequency_index\DC_Blocker_block.vhd
-- Created: 2021-01-31 19:41:13
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DC_Blocker_block
-- Source Path: max_10_frequency_index/max_10_index_frequency/DC_Blocker
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DC_Blocker_block IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        wave_out                          :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12
        );
END DC_Blocker_block;


ARCHITECTURE rtl OF DC_Blocker_block IS

  -- Component Declarations
  COMPONENT DC_Blocker
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          in0                             :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          out0                            :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DC_Blocker
    USE ENTITY work.DC_Blocker(rtl);

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Constant_out1                    : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL Subtract_sub_cast                : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Subtract_sub_cast_1              : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Subtract_out1                    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL out0                             : std_logic_vector(11 DOWNTO 0);  -- ufix12

BEGIN
  u_DC_Blocker : DC_Blocker
    PORT MAP( clk => clk,
              enb => enb,
              in0 => std_logic_vector(Subtract_out1),  -- sfix12
              out0 => out0  -- sfix12
              );

  In1_unsigned <= unsigned(In1);

  Constant_out1 <= to_unsigned(16#800#, 12);

  Subtract_sub_cast <= signed(In1_unsigned);
  Subtract_sub_cast_1 <= signed(Constant_out1);
  Subtract_out1 <= Subtract_sub_cast - Subtract_sub_cast_1;

  wave_out <= out0;

END rtl;

