// -------------------------------------------------------------
// 
// File Name: D:\Salukat\Development\Software\Quartus\MAX_10_Plus\Sine_Wave\sine_wave\raw_sine_wave.v
// Created: 2021-02-18 14:48:56
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// wave_out                      ce_out        1e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: raw_sine_wave
// Source Path: sine_wave/raw_sine_wave
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module raw_sine_wave
          (clk,
           reset,
           clk_enable,
           Enable,
           ce_out,
           wave_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   Enable;
  output  ce_out;
  output  [15:0] wave_out;  // uint16


  wire signed [15:0] enable_sine_wave_out1;  // int16
  wire [15:0] Data_Type_Conversion_out1;  // uint16


  enable_sine_wave u_enable_sine_wave (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .Enable(Enable),
                                       .wave_out(enable_sine_wave_out1)  // int16
                                       );

  assign Data_Type_Conversion_out1 = enable_sine_wave_out1;



  assign wave_out = Data_Type_Conversion_out1;

  assign ce_out = clk_enable;

endmodule  // raw_sine_wave

