// -------------------------------------------------------------
// 
// File Name: D:\Salukat\Development\Software\Quartus\MAX_10_Plus\Sine_Wave\sine_wave\Sine_Wave.v
// Created: 2021-02-18 13:03:36
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sine_Wave
// Source Path: sine_wave/raw_sine_wave/enable_sine_wave/Sine Wave
// Hierarchy Level: 2
// 
// Sine Wave
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sine_Wave
          (clk,
           reset,
           enb,
           Sine_Wave_out1);


  input   clk;
  input   reset;
  input   enb;
  output  signed [15:0] Sine_Wave_out1;  // sfix16_En14


  reg [7:0] address_cnt1;  // ufix8
  wire [7:0] Lookup_Table3_k;  // ufix8
  wire signed [15:0] Lookup_Table3_table_data [0:199];  // sfix16_En14 [200]
  wire signed [15:0] lut1out1;  // sfix16_En14


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 199
  always @(posedge clk or posedge reset)
    begin : Sine_Wave_addrcnt_temp_process1_process
      if (reset == 1'b1) begin
        address_cnt1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          if (address_cnt1 >= 8'b11000111) begin
            address_cnt1 <= 8'b00000000;
          end
          else begin
            address_cnt1 <= address_cnt1 + 8'b00000001;
          end
        end
      end
    end



  assign Lookup_Table3_table_data[0] = 16'sb0000000000000000;
  assign Lookup_Table3_table_data[1] = 16'sb0000001000000011;
  assign Lookup_Table3_table_data[2] = 16'sb0000010000000101;
  assign Lookup_Table3_table_data[3] = 16'sb0000011000000110;
  assign Lookup_Table3_table_data[4] = 16'sb0000100000000101;
  assign Lookup_Table3_table_data[5] = 16'sb0000101000000011;
  assign Lookup_Table3_table_data[6] = 16'sb0000101111111110;
  assign Lookup_Table3_table_data[7] = 16'sb0000110111110110;
  assign Lookup_Table3_table_data[8] = 16'sb0000111111101011;
  assign Lookup_Table3_table_data[9] = 16'sb0001000111011011;
  assign Lookup_Table3_table_data[10] = 16'sb0001001111000111;
  assign Lookup_Table3_table_data[11] = 16'sb0001010110101110;
  assign Lookup_Table3_table_data[12] = 16'sb0001011110001111;
  assign Lookup_Table3_table_data[13] = 16'sb0001100101101011;
  assign Lookup_Table3_table_data[14] = 16'sb0001101101000000;
  assign Lookup_Table3_table_data[15] = 16'sb0001110100001110;
  assign Lookup_Table3_table_data[16] = 16'sb0001111011010101;
  assign Lookup_Table3_table_data[17] = 16'sb0010000010010100;
  assign Lookup_Table3_table_data[18] = 16'sb0010001001001011;
  assign Lookup_Table3_table_data[19] = 16'sb0010001111111001;
  assign Lookup_Table3_table_data[20] = 16'sb0010010110011110;
  assign Lookup_Table3_table_data[21] = 16'sb0010011100111010;
  assign Lookup_Table3_table_data[22] = 16'sb0010100011001100;
  assign Lookup_Table3_table_data[23] = 16'sb0010101001010011;
  assign Lookup_Table3_table_data[24] = 16'sb0010101111010000;
  assign Lookup_Table3_table_data[25] = 16'sb0010110101000001;
  assign Lookup_Table3_table_data[26] = 16'sb0010111010100111;
  assign Lookup_Table3_table_data[27] = 16'sb0011000000000010;
  assign Lookup_Table3_table_data[28] = 16'sb0011000101010000;
  assign Lookup_Table3_table_data[29] = 16'sb0011001010010010;
  assign Lookup_Table3_table_data[30] = 16'sb0011001111000111;
  assign Lookup_Table3_table_data[31] = 16'sb0011010011101111;
  assign Lookup_Table3_table_data[32] = 16'sb0011011000001001;
  assign Lookup_Table3_table_data[33] = 16'sb0011011100010110;
  assign Lookup_Table3_table_data[34] = 16'sb0011100000010101;
  assign Lookup_Table3_table_data[35] = 16'sb0011100100000110;
  assign Lookup_Table3_table_data[36] = 16'sb0011100111101001;
  assign Lookup_Table3_table_data[37] = 16'sb0011101010111100;
  assign Lookup_Table3_table_data[38] = 16'sb0011101110000001;
  assign Lookup_Table3_table_data[39] = 16'sb0011110000110111;
  assign Lookup_Table3_table_data[40] = 16'sb0011110011011110;
  assign Lookup_Table3_table_data[41] = 16'sb0011110101110101;
  assign Lookup_Table3_table_data[42] = 16'sb0011110111111101;
  assign Lookup_Table3_table_data[43] = 16'sb0011111001110101;
  assign Lookup_Table3_table_data[44] = 16'sb0011111011011110;
  assign Lookup_Table3_table_data[45] = 16'sb0011111100110110;
  assign Lookup_Table3_table_data[46] = 16'sb0011111101111111;
  assign Lookup_Table3_table_data[47] = 16'sb0011111110110111;
  assign Lookup_Table3_table_data[48] = 16'sb0011111111100000;
  assign Lookup_Table3_table_data[49] = 16'sb0011111111111000;
  assign Lookup_Table3_table_data[50] = 16'sb0100000000000000;
  assign Lookup_Table3_table_data[51] = 16'sb0011111111111000;
  assign Lookup_Table3_table_data[52] = 16'sb0011111111100000;
  assign Lookup_Table3_table_data[53] = 16'sb0011111110110111;
  assign Lookup_Table3_table_data[54] = 16'sb0011111101111111;
  assign Lookup_Table3_table_data[55] = 16'sb0011111100110110;
  assign Lookup_Table3_table_data[56] = 16'sb0011111011011110;
  assign Lookup_Table3_table_data[57] = 16'sb0011111001110101;
  assign Lookup_Table3_table_data[58] = 16'sb0011110111111101;
  assign Lookup_Table3_table_data[59] = 16'sb0011110101110101;
  assign Lookup_Table3_table_data[60] = 16'sb0011110011011110;
  assign Lookup_Table3_table_data[61] = 16'sb0011110000110111;
  assign Lookup_Table3_table_data[62] = 16'sb0011101110000001;
  assign Lookup_Table3_table_data[63] = 16'sb0011101010111100;
  assign Lookup_Table3_table_data[64] = 16'sb0011100111101001;
  assign Lookup_Table3_table_data[65] = 16'sb0011100100000110;
  assign Lookup_Table3_table_data[66] = 16'sb0011100000010101;
  assign Lookup_Table3_table_data[67] = 16'sb0011011100010110;
  assign Lookup_Table3_table_data[68] = 16'sb0011011000001001;
  assign Lookup_Table3_table_data[69] = 16'sb0011010011101111;
  assign Lookup_Table3_table_data[70] = 16'sb0011001111000111;
  assign Lookup_Table3_table_data[71] = 16'sb0011001010010010;
  assign Lookup_Table3_table_data[72] = 16'sb0011000101010000;
  assign Lookup_Table3_table_data[73] = 16'sb0011000000000010;
  assign Lookup_Table3_table_data[74] = 16'sb0010111010100111;
  assign Lookup_Table3_table_data[75] = 16'sb0010110101000001;
  assign Lookup_Table3_table_data[76] = 16'sb0010101111010000;
  assign Lookup_Table3_table_data[77] = 16'sb0010101001010011;
  assign Lookup_Table3_table_data[78] = 16'sb0010100011001100;
  assign Lookup_Table3_table_data[79] = 16'sb0010011100111010;
  assign Lookup_Table3_table_data[80] = 16'sb0010010110011110;
  assign Lookup_Table3_table_data[81] = 16'sb0010001111111001;
  assign Lookup_Table3_table_data[82] = 16'sb0010001001001011;
  assign Lookup_Table3_table_data[83] = 16'sb0010000010010100;
  assign Lookup_Table3_table_data[84] = 16'sb0001111011010101;
  assign Lookup_Table3_table_data[85] = 16'sb0001110100001110;
  assign Lookup_Table3_table_data[86] = 16'sb0001101101000000;
  assign Lookup_Table3_table_data[87] = 16'sb0001100101101011;
  assign Lookup_Table3_table_data[88] = 16'sb0001011110001111;
  assign Lookup_Table3_table_data[89] = 16'sb0001010110101110;
  assign Lookup_Table3_table_data[90] = 16'sb0001001111000111;
  assign Lookup_Table3_table_data[91] = 16'sb0001000111011011;
  assign Lookup_Table3_table_data[92] = 16'sb0000111111101011;
  assign Lookup_Table3_table_data[93] = 16'sb0000110111110110;
  assign Lookup_Table3_table_data[94] = 16'sb0000101111111110;
  assign Lookup_Table3_table_data[95] = 16'sb0000101000000011;
  assign Lookup_Table3_table_data[96] = 16'sb0000100000000101;
  assign Lookup_Table3_table_data[97] = 16'sb0000011000000110;
  assign Lookup_Table3_table_data[98] = 16'sb0000010000000101;
  assign Lookup_Table3_table_data[99] = 16'sb0000001000000011;
  assign Lookup_Table3_table_data[100] = 16'sb0000000000000000;
  assign Lookup_Table3_table_data[101] = 16'sb1111110111111101;
  assign Lookup_Table3_table_data[102] = 16'sb1111101111111011;
  assign Lookup_Table3_table_data[103] = 16'sb1111100111111010;
  assign Lookup_Table3_table_data[104] = 16'sb1111011111111011;
  assign Lookup_Table3_table_data[105] = 16'sb1111010111111101;
  assign Lookup_Table3_table_data[106] = 16'sb1111010000000010;
  assign Lookup_Table3_table_data[107] = 16'sb1111001000001010;
  assign Lookup_Table3_table_data[108] = 16'sb1111000000010101;
  assign Lookup_Table3_table_data[109] = 16'sb1110111000100101;
  assign Lookup_Table3_table_data[110] = 16'sb1110110000111001;
  assign Lookup_Table3_table_data[111] = 16'sb1110101001010010;
  assign Lookup_Table3_table_data[112] = 16'sb1110100001110001;
  assign Lookup_Table3_table_data[113] = 16'sb1110011010010101;
  assign Lookup_Table3_table_data[114] = 16'sb1110010011000000;
  assign Lookup_Table3_table_data[115] = 16'sb1110001011110010;
  assign Lookup_Table3_table_data[116] = 16'sb1110000100101011;
  assign Lookup_Table3_table_data[117] = 16'sb1101111101101100;
  assign Lookup_Table3_table_data[118] = 16'sb1101110110110101;
  assign Lookup_Table3_table_data[119] = 16'sb1101110000000111;
  assign Lookup_Table3_table_data[120] = 16'sb1101101001100010;
  assign Lookup_Table3_table_data[121] = 16'sb1101100011000110;
  assign Lookup_Table3_table_data[122] = 16'sb1101011100110100;
  assign Lookup_Table3_table_data[123] = 16'sb1101010110101101;
  assign Lookup_Table3_table_data[124] = 16'sb1101010000110000;
  assign Lookup_Table3_table_data[125] = 16'sb1101001010111111;
  assign Lookup_Table3_table_data[126] = 16'sb1101000101011001;
  assign Lookup_Table3_table_data[127] = 16'sb1100111111111110;
  assign Lookup_Table3_table_data[128] = 16'sb1100111010110000;
  assign Lookup_Table3_table_data[129] = 16'sb1100110101101110;
  assign Lookup_Table3_table_data[130] = 16'sb1100110000111001;
  assign Lookup_Table3_table_data[131] = 16'sb1100101100010001;
  assign Lookup_Table3_table_data[132] = 16'sb1100100111110111;
  assign Lookup_Table3_table_data[133] = 16'sb1100100011101010;
  assign Lookup_Table3_table_data[134] = 16'sb1100011111101011;
  assign Lookup_Table3_table_data[135] = 16'sb1100011011111010;
  assign Lookup_Table3_table_data[136] = 16'sb1100011000010111;
  assign Lookup_Table3_table_data[137] = 16'sb1100010101000100;
  assign Lookup_Table3_table_data[138] = 16'sb1100010001111111;
  assign Lookup_Table3_table_data[139] = 16'sb1100001111001001;
  assign Lookup_Table3_table_data[140] = 16'sb1100001100100010;
  assign Lookup_Table3_table_data[141] = 16'sb1100001010001011;
  assign Lookup_Table3_table_data[142] = 16'sb1100001000000011;
  assign Lookup_Table3_table_data[143] = 16'sb1100000110001011;
  assign Lookup_Table3_table_data[144] = 16'sb1100000100100010;
  assign Lookup_Table3_table_data[145] = 16'sb1100000011001010;
  assign Lookup_Table3_table_data[146] = 16'sb1100000010000001;
  assign Lookup_Table3_table_data[147] = 16'sb1100000001001001;
  assign Lookup_Table3_table_data[148] = 16'sb1100000000100000;
  assign Lookup_Table3_table_data[149] = 16'sb1100000000001000;
  assign Lookup_Table3_table_data[150] = 16'sb1100000000000000;
  assign Lookup_Table3_table_data[151] = 16'sb1100000000001000;
  assign Lookup_Table3_table_data[152] = 16'sb1100000000100000;
  assign Lookup_Table3_table_data[153] = 16'sb1100000001001001;
  assign Lookup_Table3_table_data[154] = 16'sb1100000010000001;
  assign Lookup_Table3_table_data[155] = 16'sb1100000011001010;
  assign Lookup_Table3_table_data[156] = 16'sb1100000100100010;
  assign Lookup_Table3_table_data[157] = 16'sb1100000110001011;
  assign Lookup_Table3_table_data[158] = 16'sb1100001000000011;
  assign Lookup_Table3_table_data[159] = 16'sb1100001010001011;
  assign Lookup_Table3_table_data[160] = 16'sb1100001100100010;
  assign Lookup_Table3_table_data[161] = 16'sb1100001111001001;
  assign Lookup_Table3_table_data[162] = 16'sb1100010001111111;
  assign Lookup_Table3_table_data[163] = 16'sb1100010101000100;
  assign Lookup_Table3_table_data[164] = 16'sb1100011000010111;
  assign Lookup_Table3_table_data[165] = 16'sb1100011011111010;
  assign Lookup_Table3_table_data[166] = 16'sb1100011111101011;
  assign Lookup_Table3_table_data[167] = 16'sb1100100011101010;
  assign Lookup_Table3_table_data[168] = 16'sb1100100111110111;
  assign Lookup_Table3_table_data[169] = 16'sb1100101100010001;
  assign Lookup_Table3_table_data[170] = 16'sb1100110000111001;
  assign Lookup_Table3_table_data[171] = 16'sb1100110101101110;
  assign Lookup_Table3_table_data[172] = 16'sb1100111010110000;
  assign Lookup_Table3_table_data[173] = 16'sb1100111111111110;
  assign Lookup_Table3_table_data[174] = 16'sb1101000101011001;
  assign Lookup_Table3_table_data[175] = 16'sb1101001010111111;
  assign Lookup_Table3_table_data[176] = 16'sb1101010000110000;
  assign Lookup_Table3_table_data[177] = 16'sb1101010110101101;
  assign Lookup_Table3_table_data[178] = 16'sb1101011100110100;
  assign Lookup_Table3_table_data[179] = 16'sb1101100011000110;
  assign Lookup_Table3_table_data[180] = 16'sb1101101001100010;
  assign Lookup_Table3_table_data[181] = 16'sb1101110000000111;
  assign Lookup_Table3_table_data[182] = 16'sb1101110110110101;
  assign Lookup_Table3_table_data[183] = 16'sb1101111101101100;
  assign Lookup_Table3_table_data[184] = 16'sb1110000100101011;
  assign Lookup_Table3_table_data[185] = 16'sb1110001011110010;
  assign Lookup_Table3_table_data[186] = 16'sb1110010011000000;
  assign Lookup_Table3_table_data[187] = 16'sb1110011010010101;
  assign Lookup_Table3_table_data[188] = 16'sb1110100001110001;
  assign Lookup_Table3_table_data[189] = 16'sb1110101001010010;
  assign Lookup_Table3_table_data[190] = 16'sb1110110000111001;
  assign Lookup_Table3_table_data[191] = 16'sb1110111000100101;
  assign Lookup_Table3_table_data[192] = 16'sb1111000000010101;
  assign Lookup_Table3_table_data[193] = 16'sb1111001000001010;
  assign Lookup_Table3_table_data[194] = 16'sb1111010000000010;
  assign Lookup_Table3_table_data[195] = 16'sb1111010111111101;
  assign Lookup_Table3_table_data[196] = 16'sb1111011111111011;
  assign Lookup_Table3_table_data[197] = 16'sb1111100111111010;
  assign Lookup_Table3_table_data[198] = 16'sb1111101111111011;
  assign Lookup_Table3_table_data[199] = 16'sb1111110111111101;
  assign Lookup_Table3_k = (address_cnt1 == 8'b00000000 ? 8'b00000000 :
              (address_cnt1 >= 8'b11000111 ? 8'b11000111 :
              address_cnt1));
  assign lut1out1 = Lookup_Table3_table_data[Lookup_Table3_k];



  assign Sine_Wave_out1 = lut1out1;

endmodule  // Sine_Wave

